### ISSUE TITLE
Getting CPU Temperature in /sys

### ISSUE THREAD

**Issue by rgaufman** [balena-os/balena-intel#163]
Hi there,

I am trying your Resin img file on an Intel NUC and while it is working beautifully, I am not able to find the relevant files in /sys to check the CPU temperature.

I had a look and it seems these files are missing in /lib/modules:

```
/lib/modules/*/kernel/drivers/hwmon/coretemp.ko
/lib/modules/*/kernel/drivers/hwmon/nct6775.ko
```

Could these please be added in the next version?

**Comment by floion** [comment]
@shaunmulligan again another request which will increase the rootfs size.
Any progress on meta-balena about being able to increase the rootfs size in future releases?

**Comment by rgaufman** [comment]
Any update on this? 🙂

**Comment by floion** [comment]
Hi, no update yet. We created https://github.com/balena-os/meta-balena/issues/1366 so when we have the rootfs smaller only then we can include additional drivers in.

**Comment by rgaufman** [comment]
It seems the other ticket was done, can this be added now?

**Comment by floion** [comment]
Hi. Thanks for the nudge. Will PR it so that it will be in 2.31.0+rev2 or newer

**Comment by floion** [comment]
This should be fixed by https://github.com/balena-os/balena-intel/pull/193
