### ISSUE TITLE
Update getting started link

### ISSUE THREAD

**Issue by shaunmulligan** [balena-os/balena-intel#169]
https://github.com/balena-os/resin-intel/blob/f0df498b5324a946941ea50ebacc993f300745a2/genericx86-64.coffee#L38-L40

should be changed to point to https://www.balena.io/docs/learn/getting-started/intel-nuc/nodejs/

**Comment by floion** [comment]
@shaunmulligan so shall we change the getting started links for all the boards in the same fashion as you suggested here?

**Comment by floion** [comment]
@garethtdavies are you the person to go about this sort of bugs?

**Comment by garethtdavies** [comment]
@floion yes! I've opened a PR for this and I'll go through the other repos. Specifically, on this one there are no Surface getting started docs so, for now, are the NUC docs the best place?

**Comment by floion** [comment]
I think so @garethtdavies so let's leave it like that for the moment.
Done in https://github.com/balena-os/balena-intel/pull/282
