### ISSUE TITLE
some firmware not present in the /lib/firmware after build image

### ISSUE THREAD

**Issue by ashishka** [balena-os/balena-intel#177]
Hello!

I am have builded image for genericx86-64 but some needed firmware not present here, but it need to use wifi on new inter brix. Here is this firmware:

iwlwifi-3168-21.ucode
iwlwifi-3168-22.ucode
iwlwifi-3168-27.ucode
iwlwifi-3168-29.ucode

I am added this manually, but i sure, many other people need it to be added to the
./layers/meta-resin/meta-resin-sumo/recipes-core/packagegroups/packagegroup-resin-connectivity.bbappend
./layers/poky/meta/recipes-kernel/linux-firmware/linux-firmware_git.bb 
inside this repo https://github.com/balena-os/resin-intel

Thank you!

**Comment by floion** [comment]
Hi. Thanks for the heads-up. We'll need to do some checking on the size this adds. We are already running low in the rootfs partition.

**Comment by ashishka** [comment]
This is will increase rootfs in the ~4MB

**Comment by floion** [comment]
Hi. For what wifi chipset is this for?

**Comment by ashishka** [comment]
Hi!
We use this wifi for connect gigabyte brix to lan and internet.

**Comment by floion** [comment]
4 MB is too much for us to include at this point. balena OS 3.x will either have a bigger rootfs or allow for some mechanism to let individual boards declare a need for bigger rootfs sizes. So until then, we are closing this issue
