### ISSUE TITLE
Missing firmware for built-in Intel NUC Bluetooth (ibt-18-16-1.sfi)

### ISSUE THREAD

**Issue by pdcastro** [balena-os/balena-intel#203]
_Intel NUC built in bluetooth controller not recognized_
https://forums.balena.io/t/intel-nuc-built-in-bluetooth-controller-not-recognized/6441

* NUC model number BLKNUC7i7DNH1E
* balenaOS v2.32.0+rev2
```
$ dmesg
[ 3.605811] iwlwifi 0000:01:00.0: Direct firmware load for iwlwifi-9260-th-b0-jf-b0-36.ucode failed with error -2
[ 3.605817] bluetooth hci0: Direct firmware load for intel/ibt-18-16-1.sfi failed with error -2
[ 3.605821] Bluetooth: hci0: Failed to load Intel firmware file (-2)
```

**Comment by pdcastro** [comment]
Attached: full dmesg output
[dmesg-NUC-BLKNUC7i7DNH1E.txt](https://github.com/balena-os/balena-intel/files/3116366/dmesg-NUC-BLKNUC7i7DNH1E.txt)

**Comment by floion** [comment]
Fixed by https://github.com/balena-os/balena-intel/pull/206
