### ISSUE TITLE
Add kernel module(s) for TPM 2.0

### ISSUE THREAD

**Issue by rquackenbush** [balena-os/balena-intel#218]
We would like to have TPM 2.0 support in Balena on the Intel NUC platform.

# Use Case

We're using TPM 2.0 modules to sign tokens on the edge to identify edge devices to our cloud tier. Using the TPM is more secure than storing certs on the device because the private key never leaves the TPM.

# Solution

Add kernel support for TPM. I'm not sure exactly what modules will need to be included, but there are some clues here:

https://askubuntu.com/questions/414747/does-ubuntu-use-tpm-2-0-chip

# Expected Interfaces

When TPM 2.0 support is present, we expect to see the following files:

```
/dev/tpm0
/dev/tpmrm0
```

Original forum thread:
https://forums.balena.io/t/intel-nuc-and-tpm/3785/18

**Comment by floion** [comment]
Fixed by https://github.com/balena-os/balena-intel/pull/221
This will be available in release 2.38.0+rev1 or newer
