### ISSUE TITLE
Run in Non-Flasher Mode

### ISSUE THREAD

**Issue by sako0938** [balena-os/balena-intel#238]
I am looking to be able to run this code on a NUC-like device, and I would like it to have the same workflow as the Raspberry Pi and Odroid devices. That way I can boot the OS from the MicroSD card, and always be running off the MicroSD card.

The part which seems most promising to me is here:
On the Pi3:
raspberrypi3.coffee
```
	yocto:
		machine: 'raspberrypi3'
		image: 'resin-image'
		fstype: 'resinos-img'
		version: 'yocto-warrior'
		deployArtifact: 'resin-image-raspberrypi3.resinos-img'
		compressed: true
```
On the NUC:
genericx86-64.coffee
```

	yocto:
		machine: 'genericx86-64'
		image: 'resin-image-flasher'
		fstype: 'resinos-img'
		version: 'yocto-warrior'
		deployArtifact: 'resin-image-flasher-genericx86-64.resinos-img'
		compressed: true
```
If I just switched from resin-image-flasher to resin-image, would that create a non-flasher image?

Is there anything special that I need to put into the local.conf file? If I just change this .coffee file will the barys build program build correctly?

My first attempt at a contribution at Balena, thanks for any help!

**Comment by alexgg** [comment]
Recent version of balenaOS can boot from a non-flasher image. You can unwrap the flasher image using https://github.com/balena-os/balena-image-flasher-unwrap, program that into for example a USB drive, configure your BIOS to boot from USB and boot balenaOS directly from the USB stick.
