### ISSUE TITLE
Running Systemd with DBUS enabled can Brick the host OS if services in the container fail to properly stop.

### ISSUE THREAD

**Issue by ned-kelly** [balena-os/balena-intel#250]
Hi guys,

So I'm new to Balena and have been trying to build a large scale 'kiosk' deployment using the platform....

In essence:
- I'm running the Balena Intel OS on a bunch of Intel Compute Sticks (So I can use GPU)
- I've got a multi-container deployment with various micro-services running on the stick, one-of which is Chromium on top of x11...
- In order to track the insert/removal of portable media devices (USB Sticks) I'm monitoring udev messages, and hooking various services inside the x11 container with systemd (this container also has dbus enabled in it)....
- If a systemd service in the x11 container fails to properly stop, and I issue new release code, the system will  try and stop/restart the containers (as expected) **HOWEVER**... the messages from the child container seem to hook into the host balena-os, giving the following message in the balena cloud: `balena "Failed to activate service 'org.freedesktop.systemd1':"`.

The problem, is that once this has happened - it's virtually impossible to recover the device - if you reboot it, the device will just be stuck with: `random: crng init done` messages in the boot log which seems to block the rest of the OS services (such as networking etc) from loading...

Not an issue today because I'm still developing, so I can just reflash the device, however if this was in the field with this bug - we'd be recalling 100's of devices...

Happy to give you Balena cloud access to my container/git if you need to recreate the bug also.

Cheers,

**Comment by floion** [comment]
Hi. First of all, are you following https://www.balena.io/docs/reference/base-images/base-images/#working-with-dynamically-plugged-devices ? Do you absolutely need systemd in your container or could you just use udev as detailed in the docs from the above link?
