### ISSUE TITLE
SurfaceGo: Should mention disabling secure boot in the instructions

### ISSUE THREAD

**Issue by thgreasi** [balena-os/balena-intel#280]
A user following the instructions in the dashboard, was getting a "secure boot failed" error.
Since we also don't have docs with instructions for the surface go, it would be great to have an extra step in the provisioning instructions.

**Comment by floion** [comment]
Implemented by https://github.com/balena-os/balena-intel/pull/401
Will be available in 2.83.18+rev1 or higher
