### ISSUE TITLE
Validate on Intel NUC 10th gen

### ISSUE THREAD

**Issue by Ereski** [balena-os/balena-intel#283]
The NUC image should work on a 10th gen, but apparently it doesn't.

JF: https://jel.ly.fish/fb396cce-c42f-4e71-94c7-c60192d70e98

**Comment by shaunmulligan** [comment]
Hardware sourced from https://www.cdw.com/product/intel-next-unit-of-computing-kit-10-performance-nuc10i7fnh-mini-pc-co/5881287

**Comment by floion** [comment]
For this Intel NUC variant one needs to disable Modern Standby. Just enter BIOS and set sleep type to Legacy S3 standby. It is available under POWER -> Secondary Power Settings -> Sleep Type support.
Wifi will work on balena OS release newer than 2.50.0 but eth will need to wait for a release with kernel >= 5.5

**Comment by asininemonkey** [comment]
Any timeframe on a kernel 5.5+ release? Another owner of an Intel NUC 10 here with no ethernet (wireless not an option for me).

**Comment by chriswiggins** [comment]
Hi, we've just hit this issue with a large amount of Intel NUC 10th gens we have - can we please have an ETA on 5.5?

**Comment by chriswiggins** [comment]
Is there a way we can see what the progress is behind this Jellyfish support?

**Comment by klvnptr** [comment]
We also need ethernet support for 10th gen Intel NUC. Could you please give us a timeline? Thank you.

**Comment by floion** [comment]
Hi all, the latest OS release `2.68.1+rev1` should have support for this. Can you please confirm this on your side?

**Comment by asininemonkey** [comment]
Just upgraded my NUC and switched back to the internal ethernet port and it appears to be working. Will monitor closely but so far so good. Many thanks. 🙂

**Comment by adamtec** [comment]
I have two Intel NUC 10th gen as well as two Intel NUC 8th gen that I've put on the same Balena app. I've noticed that the temperature reported by Balena is around 80C for the 10th gen while 8th gen is around 50C. Both devices are hardly working with about 2% CPU usage and similarly equipped (storage and ram). As a result, the fans are very noisy on the 10th gen devices. 8th gen devices are NUC8i7BNH and 10th gen devices are NUC10i7FNH. I can provide additional details if useful.
