### ISSUE TITLE
timedatectl reports system clock as not synced

### ISSUE THREAD

**Issue by floion** [balena-os/balena-intel#292]
In 2.47.1+rev1:

> root@localhost:~# timedatectl 
               Local time: Sun 2020-03-15 21:00:44 UTC
           Universal time: Sun 2020-03-15 21:00:44 UTC
                 RTC time: Sun 2020-03-15 21:00:44
                Time zone: n/a (UTC, +0000)
System clock synchronized: no
              NTP service: n/a
          RTC in local TZ: no

**Comment by alexgg** [comment]
Connects-to: https://github.com/balena-os/meta-balena/issues/1852

**Comment by floion** [comment]
This is fixed in 2.83.18+rev1
