### ISSUE TITLE
user requesting EG95 LTE modem support on genericx86-64

### ISSUE THREAD

**Issue by klutchell** [balena-os/balena-intel#341]
VID: 0x2C7C, PID: 0x0195,
Anysmart Technologies Co., Ltd.
EG95 LTE modem

This specific modem was added to upstream Linux in v5.8
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=f815dd5cf48b905eeecf0a2b990e9b7ab048b4f1

Rather than backport, we will get this modem support when we finish rolling out `dunfell` with kernel 5.8.
https://github.com/balena-os/balena-intel/pull/338

**Comment by alexgg** [comment]
This modem will be supported once v2.83.1+rev2 on a 5.10 kernel is released.
