### ISSUE TITLE
Documenting secure boot, resinOS in boot menu for NUC

### ISSUE THREAD

**Issue by kb2ma** [balena-os/balena-intel#362]
My attempt to install balena on an Intel NUC was blocked by secure boot being enabled on the device. I created balena-io/docs#1816 to describe the issue, and balena-io/docs#1817 to document a workaround. This work has brought up some issues, and I'd appreciate learning how to proceed.

The boot menu identifies the USB stick with balenaOS as 'resinOS', as you can see in the [image](https://github.com/balena-io/docs/pull/1817#discussion_r613141050) on the docs PR. For documentation purposes, should we expect to see the OS identified as 'balenaOS'? Do we plan to make this change?

I see a similar issue for MS Surface Go in #280. Do we have any idea of the scope of this issue for documentation purposes? [Edit: I guess the workaround might be different, so they should be documented separately.]

Of course I'd also appreciate any comments on the proposed Note in the docs PR.

I probably should have documented the issue here. I'm happy to close 1816 in the docs repo and move it if that's useful.

**Comment by floion** [comment]
Implemented by https://github.com/balena-os/balena-intel/pull/401
Will be available in 2.83.18+rev1 or higher
