### ISSUE TITLE
Update kernel to 5.10

### ISSUE THREAD

**Issue by mtoman** [balena-os/balena-intel#376]
The motivation (among others) is that we lack support for recent Intel peripherals (Coffee Lake and above, at least some SATA controllers and ethernet adapters). Even though we do build the correct drivers they are not recognized because the new PCI IDs do not match.

Though theoretically we need at least 5.7, the latest longterm is 5.10 which looks like a reasonable choice.

This will very likely fix https://github.com/balena-os/balena-intel/issues/344 as well.

**Comment by alexgg** [comment]
A 5.10.21 kernel has been updated in v2.83.1+rev2
