### ISSUE TITLE
i915 firmware missing for Kaby Lake (KBL) GPUs

### ISSUE THREAD

**Issue by jakogut** [balena-os/balena-intel#590]
User reports that GPU accelerated video decode does not work, as the i915 driver is unable to load GuC firmware.

```
[ 5.180037] i915 0000:00:02.0: Direct firmware load for i915/kbl_guc_62.0.0.bin failed with error -2
[ 5.180041] i915 0000:00:02.0: [drm] GuC firmware i915/kbl_guc_62.0.0.bin: fetch failed with error -2
[ 5.180043] i915 0000:00:02.0: [drm] GuC firmware(s) can be downloaded from https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/i915
[ 5.180666] i915 0000:00:02.0: [drm] GuC is uninitialized
```

Fixed by: https://github.com/balena-os/meta-balena/pull/2897

**Comment by cakoolen** [comment]
Is there any progress on this story? I can see that the PR is slowly getting old but no real comments are made to it.

**Comment by cakoolen** [comment]
I don't see how this problem is fixed now since I cannot update my devices to a newer OS version let alone one that actually fixes the issue.
